### DISCUSSION TITLE
[Question] Multiple Values Usage

### DISCUSSION THREAD

**Discussion by bruhtus** [burningalchemist/sql_exporter#278] [Q&A] [answered]
Hello there,
I am new to prometheus exporter in general and trying to implement sql exporter with query that return multiple values.

I tried with this collector metrics:
```yaml
collector_name: postgresql

metrics:
  - metric_name: participants_weekly
    type: gauge
    help: 'Total participants this week'
    value_label: 'participants'
    values:
      - weekly
      - total_participants
    query: |
      select
      date_trunc('week', to_timestamp(created_at/1000)) as weekly,
      count(*) as total_participants
      from participants
      where attendance_status ilike 'attended'
      group by weekly
      order by weekly desc
      limit 1;
```

and then when i run `curl localhost:9399/metrics`, the metrics does not appear. I also try adding another metrics but only the above metrics does not appear.

So i want to ask, how do we use value label? or to be precise, how do we use multiple values with sql exporter?
Thank you!

**Comment by burningalchemist** [comment]
Hi @bruhtus, briefly looking over the snippet, I'd say the configuration seems correct. Expected output when using `value_label` in this scenario would be like that:

```
participants_weekly{participants="weekly"} 10
participants_weekly{participants="total_participants"} 100
```

Could you please share some logs? I'd expect some errors.

**Comment by bruhtus** [comment]
Hello @burningalchemist, thank you for the response!

I run the sql_exporter with these flags, in case this could help debugging:
```sh
./sql_exporter -config.file sql_exporter.yml -web.enable-reload
```

Is this the log you mentioned?
```sh
ts=2023-07-26T20:14:57.177Z caller=klog.go:108 level=warn func=Warningf msg="Starting SQL exporter (version=0.11.1, branch=HEAD, revision=6293d4bc7ffe9531c06779c49d9003b8c92082aa) (go=go1.20.4, platform=linux/amd64, user=root@7adcd09cb689, date=20230601-21:21:08, tags=netgo)"
ts=2023-07-26T20:14:57.178Z caller=klog.go:96 level=warn func=Warning msg="Listening on :9399"
ts=2023-07-26T20:14:57.178Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9399
ts=2023-07-26T20:14:57.178Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9399
```

The log above is after i run `curl localhost:9399/metrics` and i don't really see the change before and after i run `curl localhost:9399/metrics`, do i need to change the log level?

I also add a new query for comparison, the collector metrics would be like this:
```yaml
collector_name: postgresql

metrics:
  - metric_name: db_size
    type: gauge
    help: 'Database size'
    values:
      - db_size
    query: |
      select pg_database_size('db-name') as db_size;

  - metric_name: participants_weekly
    type: gauge
    help: 'Total participants this weeks'
    value_label: 'participants'
    values:
      - weekly
      - total_participants
    query: |
      select
      date_trunc('week', to_timestamp(created_at/1000)) as weekly,
      count(*) as total_participants
      from participants
      where attendance_status ilike 'attended'
      group by weekly
      order by weekly desc
      limit 1;
```

and this is the screenshot when i run `curl localhost:9399/metrics`:
![image](https://github.com/burningalchemist/sql_exporter/assets/44498173/37a8a74d-1ae5-4f83-bc2d-78a6cbc5133c)

In case this could help debugging, this is my `sql_exporter.yml`:
```yaml
# Global defaults.
global:
  # Subtracted from Prometheus' scrape_timeout to give us some headroom and prevent Prometheus from timing out first.
  scrape_timeout_offset: 500ms
  # Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
  min_interval: 0s
  # Maximum number of open connections to any one target. Metric queries will run concurrently on multiple connections,
  # as will concurrent scrapes.
  max_connections: 3
  # Maximum number of idle connections to any one target. Unless you use very long collection intervals, this should
  # always be the same as max_connections.
  max_idle_connections: 3
  # Maximum number of maximum amount of time a connection may be reused. Expired connections may be closed lazily before reuse.
  # If 0, connections are not closed due to a connection's age.
  max_connection_lifetime: 5m

# The target to monitor and the collectors to execute on it.
target:
  # Data source name always has a URI schema that matches the driver name. In some cases (e.g. MySQL)
  # the schema gets dropped or replaced to match the driver expected DSN format.
  data_source_name: 'postgresql://user:password@localhost:5432/db-name'

  # Collectors (referenced by name) to execute on the target.
  # Glob patterns are supported (see <https://pkg.go.dev/path/filepath#Match> for syntax).
  collectors: [postgresql]

# Collector files specifies a list of globs. One collector definition is read from each matching file.
# Glob patterns are supported (see <https://pkg.go.dev/path/filepath#Match> for syntax).
collector_files:
  - 'postgresql.collector.yml'
```

Let me know if you need another information.
