### DISCUSSION TITLE
Different collector file for each differrent job

### DISCUSSION THREAD

**Discussion by JesusFrontelo** [burningalchemist/sql_exporter#348] [Q&A] [answered]
Hi, 

I´m trying to config multiple jobs, and i want to use different collector files for some specific jobs. Is there a way to acomplish that?
i´m getting the error ` level=error func=Fatalf msg="Error creating exporter: unknown fields in job: collector_files" ` when i try to add collector_files field to a job. 

for example: 
````
jobs:
  - job_name: DB-NAME1
    collector_files:
      - /path/to/collector_file/collector1.yml
    static_configs:
        - targets:
            Database1: 'pg://user@*.*.*.*:3306/postgres?sslmode=disable'
  - job_name: DB-NAME2
    collector_files:
      - /path/to/collector_file/collector2.yml
    static_configs:
        - targets:
            Database2: 'pg://user@*.*.*.*:3306/postgres?sslmode=disable'
````

**Comment by burningalchemist** [comment, marked as answer]
Hi @JesusFrontelo, `collector_files` is a global field that defines list of available collectors loaded by sql_exporter. But you can specify different `collectors` per job like here:

```
  - job_name: test1
    collectors: [coll1]
    static_configs:
      - targets:
          data1: 'mysql://test:test@localhost:3306/test'
  - job_name: test2
    collectors: [coll2]
    static_configs:
      - targets:
          data1: 'mysql://test:test@localhost:3306/test'

```
