### DISCUSSION TITLE
Kubernetes Operator

### DISCUSSION THREAD

**Discussion by tonobo** [burningalchemist/sql_exporter#352] [Ideas]
Howdy everyone,

I'd like to have an kubernetes operator which instruments the sql exporter. I'm thinking of an "query" or maybe in sql-exporters glossar "controller" CRD. The controller is mainly used to compact the configuration for the sql exporter.

Why do i want this? Assume you have more than a single repository for your infrastructure, way more decentralized, "microservices", those query crds can be spread across multiple project, only need to be deployed to the same cluster or namespace. In how it works i'm thinking quite on how prometheus rule crd works.

Example to reflect the sample for readme:

```yaml
apiVersion: sql-exporter.burningalchemist.github.io/v1beta1
kind: Controller
metadata:
  name: pricing_data_freshness
spec:
  metrics:
    - metric_name: pricing_update_time
      type: gauge
      help: 'Time when prices for a market were last updated.'
      key_labels:
        # Populated from the `market` column of each row.
        - Market
      static_labels:
        # Arbitrary key/value pair
        portfolio: income
      values: [LastUpdateTime]
      query: |
        SELECT Market, max(UpdateTime) AS LastUpdateTime
        FROM MarketPrices
        GROUP BY Market
```
