### DISCUSSION TITLE
Help needed to deploy on Windows Server

### DISCUSSION THREAD

**Discussion by Shivam327** [burningalchemist/sql_exporter#392] [Q&A] [answered]
Hi Folks i have been trying to implement this exporter on my Machine for testing purposes but I was not able to make it 
Error: No metrics gathered, [from Gatherer #1] invalid port ":3308)" after host
sql_exporter:
```
# Global defaults.
global:
  # If scrape_timeout <= 0, no timeout is set unless Prometheus provides one. The default is 10s.
  scrape_timeout: 10s
  # Subtracted from Prometheus' scrape_timeout to give us some headroom and prevent Prometheus from timing out first.
  scrape_timeout_offset: 500ms
  # Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
  min_interval: 0s
  # Maximum number of open connections to any one target. Metric queries will run concurrently on multiple connections,
  # as will concurrent scrapes.
  max_connections: 3
  # Maximum number of idle connections to any one target. Unless you use very long collection intervals, this should
  # always be the same as max_connections.
  max_idle_connections: 3
  # Maximum number of maximum amount of time a connection may be reused. Expired connections may be closed lazily before reuse.
  # If 0, connections are not closed due to a connection's age.
  max_connection_lifetime: 5m

# The target to monitor and the collectors to execute on it.
target:
  # Data source name always has a URI schema that matches the driver name. In some cases (e.g. MySQL)
  # the schema gets dropped or replaced to match the driver expected DSN format.
  data_source_name: "mysql://root:123456@tcp(localhost:3308)/sys"
  # 'user:password@tcp(localhost:3306)/database'

  # Collectors (referenced by name) to execute on the target.
  # Glob patterns are supported (see <https://pkg.go.dev/path/filepath#Match> for syntax).
  collectors: [mssql_*]

# Collector files specifies a list of globs. One collector definition is read from each matching file.
# Glob patterns are supported (see <https://pkg.go.dev/path/filepath#Match> for syntax).
collector_files:
  - "*.collector.yml"

```

So just you give you an idea of what i am trying to Do
1) Monitor MSSQL and MySQL

Note: I have tried using Windows Exporter but I was not able to make it 
My Requirements:
I have multiple DBs installed on a bare metal Windows server, with many DBs I want to monitor all of them with the help of Grafana to monitor its performance and know the issues.
Please help me with any dashboards and queries. to monitor imp metrircs .
