### DISCUSSION TITLE
Using Helm and set job list in Terraform

### DISCUSSION THREAD

**Discussion by MacaulaySouza** [burningalchemist/sql_exporter#498] [Q&A] [answered]
Hi, 

Using values YAML I was able to set a job similar to this
```
  jobs:
    - job_name: "database_targets"
      collectors: [active_connections]
      static_configs:
        - targets:
            'database1': 'postgres://USER:PASSWORD@MY_RDS_ADDRESS:5432/postgres?sslmode=disable'
            'database2': 'postgres://USER:PASSWORD@MY_RDS_ADDRESS_DB2:5432/postgres?sslmode=disable'
          labels:
            type: sql_exporter
```

Now to improve security I want to set it as variable using terraform and only for testing purposes I tried it hardcoded. All my attempts were unsuccessful. Could you update the ReadMe with an example?

in locals I set this list
```
locals {
  job_config = [
    {
      job_name     = "database_targets"
      collectors   = ["active_connections"]
      static_configs = [
        {
          targets = {
             'database1': 'postgres://USER:PASSWORD@MY_RDS_ADDRESS:5432/postgres?sslmode=disable'
             'database2': 'postgres://USER:PASSWORD@MY_RDS_ADDRESS_DB2:5432/postgres?sslmode=disable'
          }
          labels = {
            type = "sql_exporter"
          }
        }
      ]
    }
  ] 
 }
  
  resource "helm_release" "kube_state_metrics" {
  name             = local.release_name
  create_namespace = false
  namespace        = var.namespace
  chart            = local.chart_name
  version          = var.chart_version
  repository       = "https://burningalchemist.github.io/sql_exporter"
  values           = sensitive([file("${path.module}/defaults.yml")])

   set {
      name  = "config.jobs"
      value = yamlencode(local.job_config)
    }
  }

 ```
 
 What ever I try I get
 msg="Error creating exporter: yaml: unmarshal errors:\n  line 30: cannot unmarshal !!str `- \"coll...` into []*config.JobConfig"

**Comment by burningalchemist** [comment]
Hey @MacaulaySouza it seems like the manifest produced is invalid, so it cannot be parsed by the application. Do you mind trying the reverse logic first:
```
echo 'yamldecode(file("snippet.yml"))' | terraform console
```

The content of `snippet.yml` would contain the first snippet you've shared. This should give us a valid HCL structure.

**Reply by burningalchemist** [reply, marked as answer]
Btw, here's a working example:

```yaml
jobs:
  - job_name: db_targets1
    collectors: [mydb]
    static_configs:
        - targets:
            test1: 'dsn'
          labels:
            test: test
  - job_name: db_targets2
    collectors: [mydb]
    static_configs:
        - targets:
            csv3: 'dsn'
```

It seems there's a typo in the README (extra list for labels), I'll make sure it's corrected. 👍
