### DISCUSSION TITLE
No collectors defined for target

### DISCUSSION THREAD

**Discussion by dinu111** [burningalchemist/sql_exporter#577] [General]
Hi, im a bit of a newbe when it comes to this sql exporter so I would appreciate any help.

Ok here it goes, im trying on my local machine to make this work but im using an oracle db and from what I read this is ok and can use any database as long as it has a go driver so in this sense I set up an oracle db that is working fine via a docker compose, nothing extraordinary, just some simple stuff:

![image](https://github.com/user-attachments/assets/014a2400-1e3e-43b8-baaf-a3304cda16a7)

Then I set this [go driver](https://github.com/mattn/go-oci8/tree/v0.1.1) in the "drivers_gen.go" file like so:

![image](https://github.com/user-attachments/assets/36296183-bb21-45f2-b300-65970208e262)

All good until now so I continued with building the image and testing if the driver is there and from the output it seems to be there, looks a bit weird but it seems fine.

![image](https://github.com/user-attachments/assets/1051f7de-276c-4ae5-922c-6093c7d7ed40)

Now I tried a configuration so I created a simple sql_exporter.yml that looks like so and would do a simple test on the database:

```
global:
  max_connections: 3
  max_idle_connections: 3
  min_interval: 0s
  scrape_error_drop_interval: 0s
  scrape_timeout: 10s
  scrape_timeout_offset: 500ms

target:
  driver: oci8
  data_source_name: "MYCARENET/MYCARENET@localhost:1521/MYCARENET"

collectors:
  - collector_name: test_scrape
    metrics:
      - help: A test metric from Oracle
        metric_name: oracle_test_metric
        type: gauge
        values: [value]
        query: |
          SELECT 1 AS value FROM dual

```

When I execute the command:  ` /bin/sql_exporter --config.file=sql_exporter.yml --log.level=debug`
I get this error and I dont understand why?

```
ts=2024-08-29T11:41:52.178Z caller=klog.go:118 level=warn func=Warningf msg="Starting SQL exporter (version=0.15.0, branch=master, revision=03f49c6603f558f11351981a186d0c3e2043d6ab) (go=go1.23.0, platform=linux/amd64, user=root@buildkitsandbox, date=20240829-11:00:42, tags=netgo)"
ts=2024-08-29T11:41:52.178Z caller=klog.go:94 level=debug func=Infof msg="Loading configuration from sql_exporter.yml"
ts=2024-08-29T11:41:52.178Z caller=klog.go:157 level=error func=Fatalf msg="Error creating exporter: no collectors defined for target"
```

Am I misusing the configuration somehow or am I missing some configuration or maybe the driver is not correct, I am not sure. 
I would appreciate any help. Thank you in advance.

**Comment by burningalchemist** [comment]
Hi @dinu111,

several points so far:

- It's better to use `github.com/sijms/go-ora/v2` for Oracle DB;
- Once added to the drivers_gen.go, you might need to build it with make drivers-custom (or wherever you added the string to);
- target configuration is incorrect - you need to provide a single DSN string (find the example for your database [here](https://github.com/xo/dburl))
- `driver` is invalid key in the configuration, so it doesn't get loaded properly (the config file cannot be parsed);
- `collectors` key is missing for the target. The idea is that you define the collectors in the parent list, and then assign them or some of them to a particular target.

So in the end, your target configuration should be like below:
```
target:
  name: optional name for the target
  data_source_name: "driver://hostname/etc" (consult with dburl)
  collectors: [test_scrape]
```

Please have a look and let me know. 👍

**Reply by dinu111** [reply]
@burningalchemist  Thank you so much for your fast answer and input, I will try this and revert back <3.

**Reply by dinu111** [reply]
Thank you so much @burningalchemist , after applying the configuration you mentioned I can see it working as expected:

`~ $ /bin/sql_exporter --config.file=sql_exporter.yaml --log.level=debug
ts=2024-08-29T12:56:40.615Z caller=klog.go:118 level=warn func=Warningf msg="Starting SQL exporter (version=0.15.0, branch=non-git, revision=non-git) (go=go1.23.0, platform=linux/amd64, user=root@4b0581d10caa, date=20240829-12:51:07, tags=netgo)"
ts=2024-08-29T12:56:40.615Z caller=klog.go:94 level=debug func=Infof msg="Loading configuration from sql_exporter.yaml"
ts=2024-08-29T12:56:40.615Z caller=klog.go:94 level=debug func=Infof msg="Resolved collectors for target: 1"
ts=2024-08-29T12:56:40.615Z caller=klog.go:94 level=debug func=Infof msg="[] Target ping enabled: true"
ts=2024-08-29T12:56:40.615Z caller=tls_config.go:313 level=info msg="Listening on" address=[::]:9399
ts=2024-08-29T12:56:40.615Z caller=tls_config.go:316 level=info msg="TLS is disabled." http2=false address=[::]:9399`

For reference for whoever is looking for this as well this is the sql_exporter config that works, as mention by @burningalchemist.

```
global:
  max_connections: 3
  max_idle_connections: 3
  min_interval: 0s
  scrape_error_drop_interval: 0s
  scrape_timeout: 10s
  scrape_timeout_offset: 500ms

target:
  data_source_name: "oracle://MYCARENET/MYCARENET@localhost:1521/MYCARENET"
  collectors: [test_scrape]

collectors:
  - collector_name: test_scrape
    metrics:
      - help: A test metric from Oracle
        metric_name: oracle_test_metric
        type: gauge
        values: [value]
        query: |
          SELECT 1 AS value FROM dual
```

From my point of view this question can be closed.
