### DISCUSSION TITLE
timestamp_value not working with MariaDB

### DISCUSSION THREAD

**Discussion by jgosmann** [burningalchemist/sql_exporter#656] [Q&A] [answered]
**Describe the bug**
Trying to set `timestamp_value` with a query against a MariaDB database fails with this error message:

```
Error gathering metrics: [from Gatherer #1] [collector=my-collector,query=sql_exporter_test] sql: Scan error on column index 0, name \"time\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
```

**To Reproduce**
1. Create config for a metric:
   ```yaml
   metrics:
     - metric_name: sql_exporter_test
       type: gauge
       help: foo
       static_value: 1
       timestamp_value: time
       query: |
         SELECT NOW() as time FROM dual;
   ```
2. Ensure that the queried database is a MariaDB database (didn't test any other databases, might not be a problem limited to MariaDB).
3. See `sql_exporter` logs.

**Expected behavior**
A metric with timestamps collected from the given `timestamp_value` column is created.
