### DISCUSSION TITLE
SQL Exporter is Not Starting After Installation on Windows Server

### DISCUSSION THREAD

**Discussion by JabirBaig9395** [burningalchemist/sql_exporter#659] [Q&A] [answered]
Hi Team,

I have installed SQL Exporter(sql_exporter-0.16.0.windows-amd64) on windows server 2019, i have installed it using NSSM as a service using the following steps, i am getting the following error while starting the service, can some one look into this.

`C:\Windows\System32>cd C:\nssm-2.24\nssm-2.24\win64
C:\nssm-2.24\nssm-2.24\win64>dir
 Directory of C:\nssm-2.24\nssm-2.24\win64

13/12/2024  08:47    <DIR>          .
24/09/2024  07:34    <DIR>          ..
13/12/2024  08:47                 0 cd
24/09/2024  07:33           331,264 nssm.exe
               2 File(s)        331,264 bytes
               2 Dir(s)  29,061,558,272 bytes free

C:\nssm-2.24\nssm-2.24\win64>nssm.exe install sql_exporter C:\sql_exporter-0.16.0.windows-amd64\sql_exporter.exe
Service "sql_exporter" installed successfully!
`
when i am trying to start the service i am getting the following error msg
`C:\nssm-2.24\nssm-2.24\win64>sc start sql_exporter

SERVICE_NAME: sql_exporter
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 5188
        FLAGS              :`

![image](https://github.com/user-attachments/assets/08fde8f2-bb5e-4d8a-8a6f-ea92c97afcfd)

**Comment by burningalchemist** [comment]
Hi @JabirBaig9395,

With NSSM you might have some log files around with the errors from sql_exporter. Could you please share them? 

It's likely that you haven't configured the sql_exporter properly. 

Do you have sql_exporter.yml config file in place?

I would suggest first to configure and run sql_exporter without NSSM, as I can't really support you there. Once it works well, you can wrap it with NSSM.

I'll convert this issue into a discussion as it's not a bug.

**Comment by JabirBaig9395** [comment]
i have the following configuration in my sql_exporter.yml, please correct me if i am doing anything wrong
```
`# The target to monitor and the collectors to execute on it.
target:
  # Data source name always has a URI schema that matches the driver name. In some cases (e.g. MySQL)
  # the schema gets dropped or replaced to match the driver expected DSN format.
    data_source_name: 'sqlserver://pmmadmin:xxxxxxxxxxx@ix3-test.secure.mycompany.com:1433'

  # Collectors (referenced by name) to execute on the target.
  # Glob patterns are supported (see <https://pkg.go.dev/path/filepath#Match> for syntax).
  collectors: [mssql_*]

# Collector files specifies a list of globs. One collector definition is read from each matching file.
# Glob patterns are supported (see <https://pkg.go.dev/path/filepath#Match> for syntax).
collector_files: 
  - "*.collector.yml"
`
```
