### DISCUSSION TITLE
Problem using the jobs config pattern

### DISCUSSION THREAD

**Discussion by nipthisin** [burningalchemist/sql_exporter#707] [Q&A]
Hi,
I doubt this is a bug so I'm posting it here, but hope someone can help with finding the problem.

**Describe the bug**
While trying to use the 'jobs' part of the config in order to have multiple DB connections instead of 'target', I receive multiple errors.
When using just one connection with a 'target' config, it works just fine.

**To Reproduce**
I add new lines to the jobs part one by one. It gives the correct error about missing the next respective part one by one.
Until I get to the last few lines where you define the connections. Described below.

**Expected behavior**
I get to connect to at least one database without an error.

**Configuration**
It works until this point and complains with message "exactly one of 'jobs' and 'target' must be defined":
```
jobs:
- job_name: test_job
  collectors: [test_collector]
  static_configs:
   - targets:
```
 
After adding the next line there is an error "Unknown field in static_config: testname":
```
jobs:
- job_name: test_job
  collectors: [test_collector]
  static_configs:
   - targets:
     testname:
```

When only using the db string there is the error "did not find expected key":
```
jobs:
- job_name: test_job
  collectors: [test_collector]
  static_configs:
   - targets:
     : 'test'
```

*This is how it should be written because it is how it works for all the other parts of the config.* When having the full key value pair there is still the error "Unknown field in static_config: testname":
```
jobs:
- job_name: test_job
  collectors: [test_collector]
  static_configs:
   - targets:
     testname: 'test'
```

Playing with the indentation gives the error "exactly one of 'jobs' and 'target' must be defined":
```
jobs:
- job_name: test_job
  collectors: [test_collector]
  static_configs:
   - targets:
       testname: 'test'
```

**Comment by burningalchemist** [comment]
Hi @nipthisin, could you please wrap your snippets in the code block? It's mainly about the configuration definition, and sadly we're dealing with YAML design imperfections. I'm happy to assist here, though. :)

**Comment by burningalchemist** [comment]
Have a look at the working example in the README.md:
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/da1a98f9-67c4-49aa-9c5c-5f7e7d99ba22" />

The jobs/target error (`"exactly one of 'jobs' and 'target' must be defined":`) implies that you need to remove/comment out the `target` stanza (single target mode) and only keep `jobs`, otherwise sql_exporter wouldn't be able to decide which mode to run.

**Reply by nipthisin** [reply]
Thank you for answering so fast.
There is no target part in the config anymore, it's been completely replaced. That's why the messages confuse me. Looking at the code, the `"exactly one of 'jobs' and 'target' must be defined":` shows if either both 'jobs' and 'target' are defined, or neither. And I feel like it's showing up because of the 'neither'.
Copy pasting the example gives similar errors.

The full config below, with some confidential information stripped out:

```
collectors:
- collector_name: testcollector
  metrics:
  - help: helptext
    key_labels:
    - type
    metric_name: testmetric
    query: "SELECT count(*) as count FROM testschema"
    type: gauge
    value_label: sum
    values:
    - count
global:
  max_connection_lifetime: 5m
  max_connections: 3
  max_idle_connections: 3
  min_interval: 0s
  scrape_error_drop_interval: 0s
  scrape_timeout: 180s
  scrape_timeout_offset: 500ms
jobs:
- job_name: test_job
  collectors: [testcollector]
  static_configs:
   - targets:
     testname: 'test'
```

**Reply by burningalchemist** [reply]
Hey @nipthisin, your issue is here:

`static_configs` is a list of targets (with optional labels applied), where `targets` is a map(object) of keys (target names) and values (their DSNs).

So, you need to restructure it in the following way:

```
...
jobs:
- job_name: test_job
  collectors: [mssql_*]
  static_configs:
   - targets:
       testname: 'postgres://localhost:5432' <-- mind the indentation here, targets is a set/object here.
...
```

I've just tested it and it works just fine:

<img width="912" alt="image" src="https://github.com/user-attachments/assets/79be7741-12ab-4401-948a-7fe4fbd5fe90" />

**Reply by nipthisin** [reply]
As far as I can tell, that is the same as the last example in my opening post. I'll add it here again for easier reference:

```
jobs:
- job_name: test_job
  collectors: [test_collector]
  static_configs:
   - targets:
       testname: 'test'
```

Which results in the `"exactly one of 'jobs' and 'target' must be defined"` error. (I have tested it again just now to be sure)
Maybe it's our platform that is doing some weird things in the background, but I'm out of ideas. Worst case scenario we can spin up two exporters.

**Reply by burningalchemist** [reply]
Are you sure that you populate a proper DSN? In your snippet you show `testname: 'test'`, it's an incorrect target, hence the error. You need to set it to `testserver: 'your_db_schema://host/dbname'` and so on.

The format for target and jobs is different.

I think if you could paste the exact config, and then redact the sensitive values, this would help.

sql_exporter has no system dependencies, so it's unlikely to be related to your platform, to me it seems still the configuration.

**Reply by burningalchemist** [reply]
Just for the context:

```go
// checkRequiredFields checks that all required fields are present.
func (c *Config) checkRequiredFields() error {
	if (len(c.Jobs) == 0) == (c.Target == nil) {
		return fmt.Errorf("exactly one of `jobs` and `target` must be defined")
	}
	return nil
}
```

This is the function which validates the config and throws an error. So the condition here is:
- if the length of jobs list is 0, and target is also empty, then we have an issue.

Since you've mentioned that the target is commented out, so it's nil technically, then our jobs list for some reason is not populated properly.

I'd also check maybe with some yaml utility if your yaml is valid. Sometimes there some special control characters which break the config file, and it's impossible to inspect visually.

**Reply by burningalchemist** [reply]
Also, I forgot to ask in the first place - what's your version? and how you deploy it.

**Reply by nipthisin** [reply]
I'm using 'test' as an example here, but in my actual setup I use the string that works in the single 'target' config.
The whole real config isn't more than I've already shown. The 'general' and 'collectors' sections are fine because they work when using the single 'target' config. Here is the full slightly redacted version:

```
collectors:
- collector_name: performance
  metrics:
  - help: Count of actual successful performance records per type
    key_labels:
    - type
    metric_name: XXX_performance_successful_count
    query: "SELECT count(*) as count,\n    c.performance_type as type\nFROM performance.performance
      p JOIN performance.code c on p.code_id  = c.id\nGROUP BY 2 \n"
    type: gauge
    value_label: sum
    values:
    - count
global:
  max_connection_lifetime: 5m
  max_connections: 3
  max_idle_connections: 3
  min_interval: 0s
  scrape_error_drop_interval: 0s
  scrape_timeout: 180s
  scrape_timeout_offset: 500ms
jobs:
- job_name: XXX_psql_targets
  collectors: [performance]
  static_configs:
  - targets:
      pg1: 'postgresql://USER:PW@MACHINE:PORT/db_int_XXX?sslmode=disable'
```

We're on version 0.15.0. I don't have control over it but can request an update.

**Reply by burningalchemist** [reply]
Hey @nipthisin, I've taken your example, changed the DSN to my test db file, and the query, and it works without any issues:

```
collectors:
- collector_name: performance
  metrics:
  - metric_name: test
    help: Count of actual successful performance records per type
    type: gauge
    key_labels: [Username]
    values: [Identifier]
    query: |
      SET @@DELIMITER = ";";
      SELECT Username, Identifier FROM `username.csv` ;
global:
  max_connection_lifetime: 5m
  max_connections: 3
  max_idle_connections: 3
  min_interval: 0s
  scrape_error_drop_interval: 0s
  scrape_timeout: 180s
  scrape_timeout_offset: 500ms
jobs:
- job_name: XXX_psql_targets
  collectors: [performance]
  static_configs:
  - targets:
      pg1: 'csvq:/sql_exporter/test.csv'
```

If you use Kubernetes for instance and ConfigMaps, this might be something related to the mounting and potentially might create a malformed file.

I'd suggest running a standalone app locally, and validate the configuration. Even though you won't be able to access your database instance, you'd at least pass the config validation check.
