### ISSUE TITLE
Call a specific job scrape via a query string

### ISSUE THREAD

**Issue by tchabit** [burningalchemist/sql_exporter#178]
Hello,

I'm new to prometheus and trying to have a different scrapping interval for collectors, without having to configure two sql_exporter services.

Despite using the exemple here : https://github.com/burningalchemist/sql_exporter/issues/37#issuecomment-849135820 , I did not find a way for prometheus to call one specific 'job' defined in sql_exporter.yml

```
jobs:
  - job_name: test1
    collectors: [ports]
    static_configs:
      - targets:
          data1: 'mysql://test:test@localhost:3306/test'

  - job_name: test2
    collectors: [devices]
    static_configs:
      - targets:
          data2:  'mysql://test:test@localhost:3306/test'
```

With this configuration it add an instance -target db name) and job label but I dont find how to call only one "sql_exporter job" from prometheus or through curl as I dont find a way to make params works.

Am I missing something ?
