### ISSUE TITLE
Add possibility to collect metrics without SSL

### ISSUE THREAD

**Issue by sigurdblueface** [burningalchemist/sql_exporter#180]
**Is your feature request related to a problem? Please describe.**
I am getting an error `No metrics gathered, [from Gatherer #1] pq: SSL is not enabled on the server`
while trying to collect metrics from the server without SSL

**Describe the solution you'd like**
I would like to have a configuration option e.g.:
```yaml
target:
  data_source_name: 'postgres://192.168.152.23:5432'
  ssl: false
```

`?sslmode=disable` surely does the job, but a separate option imo would be more human friendly and readable
