### ISSUE TITLE
"up" metric only show in jobs mode

### ISSUE THREAD

**Issue by ZhongmingFan** [burningalchemist/sql_exporter#206]
Hello, I have noticed that the "up" metrics only seem to work when I use the job mode in the sql_exporter.yml file. Specifically, I have defined a job with the following content:
```
jobs:
  - job_name: test
    collectors: [mssql_*]
    static_configs:
      - targets:
          mssql: 'sqlserver://prom_user:prom_password@dbserver1.example.com:1433'
```
However, if I change to target mode by using the following configuration:
```
target:
   data_source_name: 'sqlserver://prom_user:prom_password@dbserver1.example.com:1433'
   collectors: [mssql_*]
```

The "up" metrics disappear.

The up metrics shows in jobs mode(this is what I want): 
up{instance="mssql",job="test"} 0

Can anyone tell me what's the problem?
