### ISSUE TITLE
connection refused when fetching metrics from Prometheus

### ISSUE THREAD

**Issue by choucavalier** [burningalchemist/sql_exporter#257]
**Describe the bug**

Prometheus gets a `connection refused` error when trying te fetch `/metrics` from `sql_exporter` on port 9399:

```
[+] Running 1/1
 ✔ Container sql-exporter  Recreated                                                                                                                                                       0.3s
Attaching to sql-exporter
sql-exporter  | ts=2023-06-05T15:04:21.377Z caller=klog.go:108 level=warn func=Warningf msg="Starting SQL exporter (version=0.11.1, branch=HEAD, revision=6293d4bc7ffe9531c06779c49d9003b8c92082
aa) (go=go1.20.4, platform=linux/amd64, user=root@buildkitsandbox, date=20230601-21:27:45, tags=netgo)"
sql-exporter  | ts=2023-06-05T15:04:21.378Z caller=klog.go:96 level=warn func=Warning msg="Listening on :9399"
sql-exporter  | ts=2023-06-05T15:04:21.379Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9399
sql-exporter  | ts=2023-06-05T15:04:21.379Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9399
```

**Configuration**

```
global:
  scrape_timeout: 10s
  scrape_timeout_offset: 500ms
  min_interval: 0s
  max_connections: 3
  max_idle_connections: 3

target:
  data_source_name: 'sqlserver://HIDDEN:HIDDEN@HIDDEN\HIDDEN:HIDDEN'

  collectors: [mssql_standard]

collector_files:
  - "*.collector.yml"
```

within my `docker-compose.yml`

```
sql-exporter:
  container_name: sql-exporter
  image: burningalchemist/sql_exporter
  restart: "unless-stopped"
  hostname: sql_exporter
  command: --config.file=/config/sql_exporter.yml
  ports:
    - 9399:9399
  volumes:
    - /opt/infra/sql_exporter:/config
```

any idea why the http request on `/metrics` on port 9399 is returning a `connection refused` error?

```
Get "http://localhost:9399/metrics": dial tcp 127.0.0.1:9399: connect: connection refused
```
