### ISSUE TITLE
Can I set an interval between collected metrics?

### ISSUE THREAD

**Issue by karenlava** [burningalchemist/sql_exporter#262]
Hello, 

I am testing prometheus and sql_exporter for the first time.
The target server is MSSQL.
I know that the `scrape_interval` value of prometheus and the `min_interval` value of sql_exporter determine the collection interval. 
But I would like to know if it is possible to set the collection interval between metric and metric .
```
collector_name: mssql_standard
metrics:
  - metric_name: mssql_local_time_seconds
    type: gauge
    help: 'Local time in seconds since epoch (Unix time).'
    values: [unix_time]
    query: |
      SELECT DATEDIFF(second, '19700101', GETUTCDATE()) AS unix_time

  - metric_name: mssql_deadlocks
    type: counter
    help: 'Number of lock requests that resulted in a deadlock.'
    values: [cntr_value]
    query: |
      SELECT cntr_value
      FROM sys.dm_os_performance_counters WITH (NOLOCK)
      WHERE counter_name = 'Number of Deadlocks/sec' AND instance_name = '_Total'
```

When the above sql_exporter is started, I want the query received from the sql server side to look like the following.
```
SELECT DATEDIFF(second, '19700101', GETUTCDATE()) AS unix_time

WAIT FOR DELAY '00:00:00:01'

SELECT cntr_value
FROM sys.dm_os_performance_counters WITH (NOLOCK)
WHERE counter_name = 'Number of Deadlocks/sec' AND instance_name = '_Total'

WAIT FOR DELAY '00:00:00:01'
```
Are you providing config values ​​for these features? Or is there a way to achieve a similar effect?
Thanks in advance.
