### ISSUE TITLE
Document multiple db connection configuration

### ISSUE THREAD

**Issue by keithf4** [burningalchemist/sql_exporter#287]
**Is your feature request related to a problem? Please describe.**

Please add documentation for connecting to multiple database with a single exporter

**Describe the solution you'd like**

I'd already started writing up a feature request to ask for multiple db connection support but then glad I went and searched closed issues. I can confirm the suggestion made in issue #37 works for PostgreSQL
```
jobs:
  - job_name: db_targets
    collectors: [crunchy_global]
    static_configs:
        - targets:
            pg1: 'pg://ccp_monitoring@127.0.0.1:25432/postgres?sslmode=disable'
            pg2: 'pg://ccp_monitoring@127.0.0.1:25432/testdb?sslmode=disable'
```
Result w/ adding a label for `current_database()` value
```
[root@cd-dc1-pg1 data]# curl localhost:9399/metrics
# HELP ccp_postgresql_version_current The current version of PostgreSQL that this exporter is running on as a 6 digit integer (######).
# TYPE ccp_postgresql_version_current gauge
ccp_postgresql_version_current{dbname="postgres",instance="pg1",job="db_targets"} 130012
ccp_postgresql_version_current{dbname="testdb",instance="pg2",job="db_targets"} 130012
# HELP ccp_wal_activity_last_5_min_size_bytes Current size in bytes of the last 5 minutes of WAL generation. Includes recycled WALs.
# TYPE ccp_wal_activity_last_5_min_size_bytes gauge
ccp_wal_activity_last_5_min_size_bytes{dbname="postgres",instance="pg1",job="db_targets"} 0
ccp_wal_activity_last_5_min_size_bytes{dbname="testdb",instance="pg2",job="db_targets"} 1.6777216e+07
```
Thanks for the excellent exporter!

**Comment by keithf4** [comment]
Actually, even better, you can connect to multiple databases and have different connections use different sets of metrics by using their own collector! This is even better than I thought!
```
jobs:
  - job_name: global_targets
    collectors: [crunchy_global]
    static_configs:
        - targets:
            pg1: 'pg://ccp_monitoring@127.0.0.1:25432/postgres?sslmode=disable'
  - job_name: per_db_targets
    collectors: [crunchy_per_db]
    static_configs:
        - targets:
            pg1: 'pg://ccp_monitoring@127.0.0.1:25432/postgres?sslmode=disable'
            pg2: 'pg://ccp_monitoring@127.0.0.1:25432/testdb?sslmode=disable'

# Collector definition files.
# Glob patterns are supported (see <https://pkg.go.dev/path/filepath#Match> for syntax).
collector_files:
  - "/etc/sql_exporter/crunchy_global_collector.yml"
  - "/etc/sql_exporter/crunchy_per_db_collector.yml"
```
