### ISSUE TITLE
runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by JustNZ** [burningalchemist/sql_exporter#293]
**Describe the bug**
execution the binary and accessing the /metrics path return into this response on the console

I do get an response from all querys - but after the /metrics path loaded the binary crashes with the error below

(I'm using the oracle driver)

```
panic: runtime error: index out of range [0] with length 0

goroutine 153 [running]:
github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0001a15e0, 0xc0000e8480)
        /home/user/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.15/command.go:796 +0x135f
github.com/sijms/go-ora/v2.(*Stmt)._query(0xc0001a15e0)
        /home/user/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.15/command.go:2386 +0x110
github.com/sijms/go-ora/v2.(*Stmt).Query_(0xc0001a15e0, {0x19fc270, 0x0, 0x433655f49aac8277?})
        /home/user/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.15/command.go:2295 +0x45b
github.com/sijms/go-ora/v2.(*Stmt).QueryContext(0xc0001a15e0, {0xff3308?, 0xc00020b8c0}, {0x19fc270, 0x0, 0x0})
        /home/user/go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.15/command.go:2362 +0x1f4
database/sql.ctxDriverStmtQuery({0xff3308, 0xc00020b8c0}, {0xff3650, 0xc0001a15e0}, {0x19fc270?, 0x0, 0x0})
        /usr/lib/golang/src/database/sql/ctxutil.go:82 +0xc4
database/sql.rowsiFromStatement({0xff3308, 0xc00020b8c0}, {0xff1c70, 0xc00017af00}, 0xc0000a8c00, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/database/sql/sql.go:2801 +0x17e
database/sql.(*Stmt).QueryContext.func1(0xc8?)
        /usr/lib/golang/src/database/sql/sql.go:2751 +0xca
database/sql.(*DB).retry(0xfb8e17142e557c05?, 0xc0004c7d18)
        /usr/lib/golang/src/database/sql/sql.go:1538 +0x47
database/sql.(*Stmt).QueryContext(0xc000192c60, {0xff3308, 0xc00020b8c0}, {0x0, 0x0, 0x0})
        /usr/lib/golang/src/database/sql/sql.go:2745 +0x196
github.com/burningalchemist/sql_exporter.(*Query).run(0xc0001df3b0, {0xff3308?, 0xc00020b8c0?}, 0x583a80cc821bf5df?)
        /home/user/local/sql_exporter/query.go:128 +0xfc
github.com/burningalchemist/sql_exporter.(*Query).Collect(0xc0001df3b0, {0xff3308, 0xc00020b8c0}, 0x35b8c314eca53c75?, 0xad9ff70d146e77d8?)
        /home/user/local/sql_exporter/query.go:82 +0x9c
github.com/burningalchemist/sql_exporter.(*collector).Collect.func1(0xb59cbde4118457ab?)
        /home/user/local/sql_exporter/collector.go:87 +0x68
created by github.com/burningalchemist/sql_exporter.(*collector).Collect
        /home/user/local/sql_exporter/collector.go:85 +0x78
```

**To Reproduce**
1. execute binary
2. access /metrics url
3. look at the error in the console

**Configuration**
```
# Global settings and defaults.
global:
  # Subtracted from Prometheus' scrape_timeout to give us some headroom and prevent Prometheus from
  # timing out first.
  scrape_timeout_offset: 500ms
  # Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
  min_interval: 0s
  # Maximum number of open connections to any one target. Metric queries will run concurrently on
  # multiple connections.
  max_connections: 3
  # Maximum number of idle connections to any one target.
  max_idle_connections: 3
  # Maximum amount of time a connection may be reused to any one target. Infinite by default.
  max_connection_lifetime: 10m

jobs:
  - job_name: databases
    collectors: [common, pluggable_db]
    static_configs:
        - targets:
            primary_db: 'oracle://USER:PASSWORD@database:1521/SERVICE'
            standby_db: 'oracle://USER:PASSWORD@database:1521/SERVICE'

# Collector definition files.
# Glob patterns are supported (see <https://pkg.go.dev/path/filepath#Match> for syntax).
collector_files:
  - /etc/sql_exporter/collector/*.yml
```

collector file content:

```
collector_name: pluggable_db

# A Prometheus metric with (optional) additional labels, value and labels populated from one query.
metrics:
  - metric_name: oracledb_cpu_utilization
    type: gauge
    help: 'CPU Utilization of the Pluggable Database'
    values: [VALUE]
    query: select value from v$sysmetric@CDB_LINK where METRIC_NAME='Host CPU Utilization (%)' and group_id=2

  - metric_name: oracledb_load
    type: gauge
    help: 'OS Load of the Pluggable Database'
    values: [VALUE]
    query: select value from v$sysmetric@CDB_LINK where METRIC_NAME='Current OS Load' and group_id=2

  - metric_name: oracledb_pga_max_memory
    type: gauge
    help: 'Max Memory of the Pluggable Database'
    values: [VALUE]
    query: select sum(pga_max_mem) / 1024 / 1024 as value from v$process

  - metric_name: oracledb_pga_used_memory
    type: gauge
    help: 'Used Memory of the Pluggable Database'
    values: [VALUE]
    query: select sum(pga_used_mem) / 1024 / 1024 as value from v$process

  - metric_name: oracledb_db_connections
    type: gauge
    help: 'Connections on the Database'
    key_labels:
      - KEY
    values: [VALUE]
    query: |
      SELECT * FROM (
        SELECT * FROM (SELECT Cast(limit_value AS NUMBER) AS max_conns, max_utilization AS peak_conns, current_utilization AS curr_conns FROM   v$resource_limit@cdb_link WHERE  resource_name = 'processes'),(
          SELECT Count(1) AS busy_conns FROM v$session@cdb_link WHERE status = 'ACTIVE')) unpivot (value FOR KEY IN(max_conns AS 'db_connections_max', peak_conns AS 'db_connections_peak', curr_conns AS 'db_connections_current', busy_conns AS 'db_connections_active'))
```
