### ISSUE TITLE
Support query parameterization

### ISSUE THREAD

**Issue by reubano** [burningalchemist/sql_exporter#296]
**Is your feature request related to a problem? Please describe.**

I would like a way to prevent SQL injection by using [bound parameters](https://go.dev/doc/database/sql-injection). This would allow one to pass in the parameters separate from the query instead of passing in the entire sql query string.

`queries.collector.yml`

```yml
collector_name: counts
metrics:
- help: Admin count
  metric_name: count
  query: 'SELECT COUNT(*) as count FROM user WHERE type = admin'
  type: gauge
  values:
  - count
```

In this case if `admin` is dynamically generated and passed to `sql_exporter` in the query, it opens up a SQL injection attack vector.

**Describe the solution you'd like**

`queries.collector.yml`

```yml
collector_name: counts
metrics:
- help: Admin count
  metric_name: count
  query: 'SELECT COUNT(*) as count FROM user WHERE type = $1'
  parameters: [admin]
  type: gauge
  values:
  - count
```

This protects against SQL injection attacks via malformed parameters.

**Describe alternatives you've considered**

[pgx](https://github.com/jackc/pgx/blob/389931396eea77f4e4b369f659a33b2bff179ae5/rows_test.go#L927) and [mssql](https://github.com/microsoft/go-mssqldb/blob/eb3842574b5d72325022022421d1ac01735f6d64/queries_test.go#L515) examples

**Additional context**

Named parameter support ([pgx](https://github.com/jackc/pgx/blob/389931396eea77f4e4b369f659a33b2bff179ae5/named_args_test.go#L23) and [mssql](https://github.com/microsoft/go-mssqldb/blob/eb3842574b5d72325022022421d1ac01735f6d64/queries_test.go#L1920-L1923)) would be awesome too.

```yml
collector_name: counts
metrics:
- help: Admin count
  metric_name: count
  query: 'SELECT COUNT(*) as count FROM user WHERE type = @type'
  parameters: 
    type: admin
  type: gauge
  values:
  - count
```
