### ISSUE TITLE
Missing job target labels

### ISSUE THREAD

**Issue by Maros112358** [burningalchemist/sql_exporter#327]
**Describe the bug**
In sql_exporter `0.12.1`, I used `labels` defined in `jobs` to add custom labels to my metrics. In sql_exporter `0.12.2`, these labels do not work anymore. I am not sure if this was intentional change, but I still see labels in the [source code](https://github.com/burningalchemist/sql_exporter/blob/b8e3a5dfb32464962fcf39d530a785092c27a4bc/config/config.go#L355)

**To Reproduce**
1. Start sql_exporter with config like below
2. Go to `/metrics`

**Expected behavior**
I expected each and every metric to have label `my_label_key=my_label_value`.

**Configuration**
Example config:
```
jobs:
  - job_name: my_job
    collectors: [mssql_standard]
    static_configs:
      - targets:
          'my_target': 'connection_string'
        labels:
          my_label_key: my_label_value
```
