### ISSUE TITLE
Context deadline exceeded error handling

### ISSUE THREAD

**Issue by Maros112358** [burningalchemist/sql_exporter#345]
**Describe the bug**
When database timeouts, error log on [line 40](https://github.com/burningalchemist/sql_exporter/blob/51333ca12c961b9b84e8cc4f996dfdfa64da1f0f/cmd/sql_exporter/promhttp.go#L40C5-L40C5) does not show in the logs, even though error log on [line 47](https://github.com/burningalchemist/sql_exporter/blob/51333ca12c961b9b84e8cc4f996dfdfa64da1f0f/cmd/sql_exporter/promhttp.go#L47) shows a list of errors, where one of them is `context deadline exceeded`.

**To Reproduce**
1. Use the config below
2. Go to `/metrics`
3. Check logs

**Expected behavior**
I expected to see `Timeout collecting metrics from target: ...`

**Configuration**
```
jobs:
  - job_name: my_job
    collectors: [mssql_timeout]
    static_configs:
      - targets:
          'my_target': 'my_connection_string'
collectors:
  - collector_name: mssql_timeout
    metrics:
      - metric_name: timeout_metrics
        type: gauge
        help: 'wait for 3 minutes in MSSQL'
        values: [xxx]
        query: |
          WAITFOR DELAY '00:03:00';
```

**Additional context**
Logs I got when reproducing the error:
```
ts=2023-10-02T12:04:36.730Z caller=klog.go:108 level=warn func=Warningf msg="Starting SQL exporter (version=0.12.3, branch=HEAD, revision=d25cd797ff6b4daa53a5b9cc29c4aee3c998cb9f) (go=go1.20.8, platform=darwin/arm64, user=root@3c5818fec6b5, date=20230920-16:18:01, tags=netgo)"
ts=2023-10-02T12:04:36.737Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9399
ts=2023-10-02T12:04:36.737Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9399
ts=2023-10-02T12:04:49.060Z caller=klog.go:124 level=error func=Errorf msg="Error gathering metrics: [from Gatherer #1] [job=\"my_job\", target=\"my_target\", collector=\"mssql_timeout\", query=\"timeout_metrics\"] context deadline exceeded"
```
