### ISSUE TITLE
Different collector file for each differrent job

### ISSUE THREAD

**Issue by JesusFrontelo** [burningalchemist/sql_exporter#347]
Hi, 

I´m trying to config multiple jobs, and i want to use different collector files for some specific jobs. Is there a way to acomplish that?
i´m getting the error ` level=error func=Fatalf msg="Error creating exporter: unknown fields in job: collector_files" ` when i try to add collector_files field to a job. 

for example: 
````
jobs:
  - job_name: DB-NAME1
    collector_files:
      - /path/to/collector_file/collector1.yml
    static_configs:
        - targets:
            Database1: 'pg://user@*.*.*.*:3306/postgres?sslmode=disable'
  - job_name: DB-NAME2
    collector_files:
      - /path/to/collector_file/collector2.yml
    static_configs:
        - targets:
            Database2: 'pg://user@*.*.*.*:3306/postgres?sslmode=disable'
````
